config/routes.rb
Rails.application.routes.draw do
  resources :tweets_reals, only: [:index, :show] do 
    collection do
      get 'display'
    end
  end

  resources :tweets, only: [:index, :show] do 
    collection do
      get 'test'
    end
  end

end

app/models/tweets_real.rb
class TweetsReal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    Rails.logger.info 'INDEX PARAMS:'
    Rails.logger.info params.inspect
    @tweets = []
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    Rails.logger.info 'SHOW PARAMS:'
    Rails.logger.info params.inspect
  end

  def test
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "JZGYoTPOZTVcvtbKYnvmY1otI"
      config.consumer_secret     = "DayfYC8hpEVxYavbejdSiOKD6YsbkDRsdAxAUMDbVG09aAubw8"
      config.access_token        = "607346453-xbJEV4cwCDvJgrGyYFHQpLc47JQ5ogiJWCkTPp08"
      config.access_token_secret = "jc8gCXsgy9O5MOiq8YsEqk0pAg1rQUWfGiZqyknlJHvUy"
    end
    # do this for each CI Center
    @tweets = client.user_timeline("Children_Intl")
    @tweets.each do |element|
      tweetid = element.id
      @tweet = client.status(tweetid)      
      # puts @tweet.hashtags[0]
    end
    # iterate through all tweets, display each tweet's words, who wrote it, and date
    #for (int i = 0; i < tweets.length; i++)
    #{
      # client.status(tweets[i].id)
    #}

    # @tweets = Twitter.user_timeline[0..4]
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def tweet
    @tweet ||= nil # TODO: make a network call and retrieve the tweet.
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tweet_params
    params[:tweet]
  end
end

app/controllers/tweets_reals_controller.rb
class TweetsRealsController < ApplicationController
  before_action :set_tweets_real, only: [:show, :edit, :update, :destroy]

  # GET /tweets_reals
  # GET /tweets_reals.json
  def index
    # @tweets_reals = TweetsReal.all
    @tweets_all = TweetsReal.order(twt_created_at: :desc) # call all tweets in descending created_at order
  end

  # GET /tweets_reals/1
  # GET /tweets_reals/1.json
  def show
  end

  def display
    @tweets_all = TweetsReal.order(twt_created_at: :desc)
  end

  # DELETE /tweets_reals/1
  # DELETE /tweets_reals/1.json
  def destroy
    @tweets_real.destroy
    respond_to do |format|
      format.html { redirect_to tweets_reals_url, notice: 'Tweets real was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweets_real
      @tweets_real = TweetsReal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweets_real_params
      params[:tweets_real]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_reals_helper.rb
module TweetsRealsHelper
end

app/views/layouts/application.html.slim
doctype html
html
	head
  		title Newsfeed
  		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  		= javascript_include_tag 'application', 'data-turbolinks-track' => true
  		= csrf_meta_tags
	body

		== yield

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets Reals</h1>

<h3>You have <%= @tweets_all.length %> tweets</h3>

<table>
  <thead>
    <tr>
      <th>tweet id</th>
      <th>username</th>
      <th>created at</th>
      <th>text</th>
    </tr>
  </thead>

  <tbody>
    <% @tweets_all.each do |tweet| %>
      <tr>
        <td><%= tweet.twt_id %></td>
        <td><%= tweet.username %></td>
        <td><%= tweet.twt_created_at %></td>
        <td><%= tweet.twt_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tweets/index.html.slim
h1 Children International
.content 
	.story.story-left
		img src="http://placekitten.com/g/63/63"
		p 
			h3 You have 
			= @tweets_all.length

	.story.story-right
		p 
			| Keffiyeh PBR&B sustainable quinoa. XOXO gentrify heirloom beard, Truffaut umami biodiesel chillwave. Aesthetic XOXO salvia 
			| bitters, cold-pressed food truck craft beer slow-carb plaid retro tofu swag biodiesel direct trade banjo. Craft beer mlkshk 
			| food truck XOXO, bespoke biodiesel wayfarers mixtape Truffaut single-origin coffee shabby chic cornhole cronut. Sustainable 
			| brunch Shoreditch master cleanse. Etsy lo-fi Banksy, street art beard bespoke dreamcatcher Schlitz Echo Park put a bird on 
			| it. Food truck single-origin coffee kitsch pork belly VHS.

		img src="http://placekitten.com/g/63/63"

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', tweets_path %>

app/views/tweets/test.html.erb
HELLO!

<%= @tweet.user.screen_name %>
<%= @tweet.text %>
<%= @tweet.created_at %>
<%= @tweet.hashtags %>

app/views/tweets_reals/_form.html.erb
<%= form_for(@tweets_real) do |f| %>
  <% if @tweets_real.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweets_real.errors.count, "error") %> prohibited this tweets_real from being saved:</h2>

      <ul>
      <% @tweets_real.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets_reals/display.html.slim
h1 Children International - Around the World
.content 
	- @tweets_all.each_with_index do |tweet|
		.story.story-left
			- if tweet.twt_center === "Children_Intl"
				a[href="http://children.org" target="tab"]
					img src="../ci_intl.png" height="63px" width="63px"
			- if tweet.twt_center === "CIBayArea"
				a[href="http://children.org/bay-area-chapter" target="tab"]
					img src="../ci_bayarea.jpg" height="63px" width="63px"
			- if tweet.twt_center === "ChildrenRD"
				a[href="http://http://childreninternational.do/" target="tab"]
					img src="../ci_dominicanrepublic.jpeg" height="63px" width="63px"
			= tweet.twt_text
		p = tweet.twt_center

app/views/tweets_reals/edit.html.erb
<h1>Editing Tweets Real</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweets_real %> |
<%= link_to 'Back', tweets_reals_path %>

app/views/tweets_reals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets Reals</h1>

<img src="http://t.co/3htr4Cy9Om" />

<h3>You have <%= @tweets_all.length %> tweets</h3>

<table>
  <thead>
    <tr>
      <th>tweet id</th>
      <th>username</th>
      <th>created at</th>
      <th>text</th>
      <th>center</th>
    </tr>
  </thead>

  <tbody>
    <% @tweets_all.each do |tweet| %>
      <tr>
        <td><%= tweet.twt_id %></td>
        <td><%= tweet.username %></td>
        <td><%= tweet.twt_created_at %></td>
        <td><%= tweet.twt_text %></td>
        <td><%= tweet.twt_center %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tweets_reals/index.html.slim
h1 Children International
.content 
	- @tweets_all.each do |tweet|
		.story.story-left
			img src="http://placekitten.com/g/63/63"
			p 
				= tweet.twt_text
	.story.story-right
		p 
			| Keffiyeh PBR&B sustainable quinoa. XOXO gentrify heirloom beard, Truffaut umami biodiesel chillwave. Aesthetic XOXO salvia 
			| bitters, cold-pressed food truck craft beer slow-carb plaid retro tofu swag biodiesel direct trade banjo. Craft beer mlkshk 
			| food truck XOXO, bespoke biodiesel wayfarers mixtape Truffaut single-origin coffee shabby chic cornhole cronut. Sustainable 
			| brunch Shoreditch master cleanse. Etsy lo-fi Banksy, street art beard bespoke dreamcatcher Schlitz Echo Park put a bird on 
			| it. Food truck single-origin coffee kitsch pork belly VHS.

		img src="http://placekitten.com/g/63/63"

app/views/tweets_reals/new.html.erb
<h1>New Tweets Real</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_reals_path %>

app/views/tweets_reals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', tweets_reals_path %>